// SPDX-License-Identifier: GPL-3.0-only
// GlyphWiki data source: reads the sharded files generated by
// tools/build-glyph-data.mjs (served next to the app under glyph-data/).
// The editor talks to no server other than the host serving its own files.

const baseUrl = new URL('glyph-data/', document.baseURI).href;

const fetchText = async (path: string) => {
  const response = await fetch(baseUrl + path);
  if (!response.ok) {
    throw new Error(`failed to load ${path}`);
  }
  return response.text();
};

// FNV-1a 32bit; must match tools/build-glyph-data.mjs
const fnv1a = (s: string) => {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
};

interface Meta {
  cpShards: number;
  maxResults: number;
}

let metaPromise: Promise<Meta> | null = null;
const getMeta = () => {
  metaPromise ??= fetchText('meta.json').then((text) => JSON.parse(text) as Meta);
  return metaPromise;
};

// A sorted key space cut into chunks; the manifest lists each chunk's first key.
class ChunkedFiles<T> {
  private manifest: Promise<string[]> | null = null;
  private chunks = new Map<string, Promise<T>>();

  constructor(private dir: string, private parse: (text: string) => T) { }

  private getManifest() {
    this.manifest ??= fetchText(`${this.dir}.txt`).then((text) => text.split('\n').filter(Boolean));
    return this.manifest;
  }

  // index of the chunk whose range contains key (chunk 0 also covers keys below it)
  async locate(key: string) {
    const firsts = await this.getManifest();
    let lo = 0;
    let hi = firsts.length - 1;
    while (lo < hi) {
      const mid = (lo + hi + 1) >> 1;
      if (firsts[mid] <= key) {
        lo = mid;
      } else {
        hi = mid - 1;
      }
    }
    return { index: lo, count: firsts.length };
  }

  async get(index: number) {
    const firsts = await this.getManifest();
    const first = firsts[index];
    let chunk = this.chunks.get(first);
    if (!chunk) {
      chunk = fetchText(`${this.dir}/${encodeURIComponent(first)}.txt`).then(this.parse);
      chunk.catch(() => this.chunks.delete(first)); // allow retry
      this.chunks.set(first, chunk);
    }
    return chunk;
  }
}

const dataChunks = new ChunkedFiles('d', (text) => {
  const map = new Map<string, string>();
  for (const line of text.split('\n')) {
    const tab = line.indexOf('\t');
    if (tab > 0) {
      map.set(line.slice(0, tab), line.slice(tab + 1));
    }
  }
  return map;
});

const nameChunks = new ChunkedFiles('n', (text) => text.split('\n').filter(Boolean));

const lookup = async (name: string) => {
  const { index } = await dataChunks.locate(name);
  return (await dataChunks.get(index)).get(name);
};

// Same contract as GlyphWiki's get_source.cgi: '' when the glyph doesn't exist.
// Versioned names (u963f@9) resolve to that exact version when it was
// referenced by some glyph, otherwise to the newest version.
export const getSource = async (name: string): Promise<string> => {
  const data = await lookup(name);
  if (typeof data === 'string') {
    return data;
  }
  const at = name.indexOf('@');
  if (at > 0) {
    return (await lookup(name.slice(0, at))) ?? '';
  }
  return '';
};

const cpShards = new Map<number, Promise<Map<string, [string[], string[]]>>>();
const getCodepointEntry = async (hex: string) => {
  const { cpShards: shardCount } = await getMeta();
  const shard = fnv1a(hex) % shardCount;
  let promise = cpShards.get(shard);
  if (!promise) {
    promise = fetchText(`c/${shard}.txt`).then((text) => {
      const map = new Map<string, [string[], string[]]>();
      for (const line of text.split('\n')) {
        const [key, byName, byRelated] = line.split('\t');
        if (key) {
          map.set(key, [
            byName ? byName.split(' ') : [],
            byRelated ? byRelated.split(' ') : [],
          ]);
        }
      }
      return map;
    });
    promise.catch(() => cpShards.delete(shard));
    cpShards.set(shard, promise);
  }
  return (await promise).get(hex) ?? [[], []] as [string[], string[]];
};

const prefixScan = async (prefix: string, limit: number) => {
  const hits: string[] = [];
  const { index: start, count } = await nameChunks.locate(prefix);
  for (let index = start; index < count && hits.length < limit; index++) {
    const chunk = await nameChunks.get(index);
    for (const n of chunk) {
      if (n.startsWith(prefix)) {
        hits.push(n);
        if (hits.length >= limit) {
          break;
        }
      } else if (n > prefix) {
        return hits;
      }
    }
  }
  return hits;
};

// Same contract and rules as kage-server.mjs's search4ge.cgi:
// tab-separated names, 'tooshort' or 'nodata'.
export const search = async (query: string): Promise<string> => {
  if (!query) {
    return 'nodata';
  }
  const { maxResults } = await getMeta();
  const merge = (...lists: string[][]) => [...new Set(lists.flat())].slice(0, maxResults);

  const cp = query.codePointAt(0)!;
  if (cp > 0x2000 && [...query].length <= 2) {
    const hex = cp.toString(16);
    const [byName, byRelated] = await getCodepointEntry(hex);
    const merged = merge(byName, byRelated);
    if (merged.length) {
      return merged.join('\t');
    }
    return (await prefixScan(`u${hex}`, maxResults)).join('\t') || 'nodata';
  }

  // all glyph names are lowercase
  const q = query.toLowerCase();
  if (q.length < 5) {
    return 'tooshort';
  }
  const hits = await prefixScan(q, maxResults);
  // a unicode glyph name also brings glyphs whose related anchor is that codepoint
  const qm = /^u([0-9a-f]{4,6})(?=$|[-@])/.exec(q);
  const related = qm ? (await getCodepointEntry(qm[1]))[1] : [];
  // (kage-server's substring fallback needs the full name list and is not offered here)
  return merge(hits, related).join('\t') || 'nodata';
};
